export const FETCH_QUESTIONNAIRES = 'FETCH_QUESTIONNAIRES';

export const FETCH_QUESTIONNAIRE_BY_KEY = 'FETCH_QUESTIONNAIRE_BY_KEY';

export const SAVE_QUESTIONNAIRE = 'SAVE_QUESTIONNAIRE';

export const UPDATE_QUESTIONNAIRE = 'UPDATE_QUESTIONNAIRE';