export const FETCH_QUESTIONNAIRES = 'FETCH_QUESTIONNAIRES';

export const FETCH_QUESTIONNAIRE_BY_KEY = 'FETCH_QUESTIONNAIRE_BY_KEY';

export const SAVE_QUESTIONNAIRE = 'SAVE_QUESTIONNAIRE';

export const UPDATE_QUESTIONNAIRE = 'UPDATE_QUESTIONNAIRE';

export const ARCHIVE_QUESTIONNAIRE = 'ARCHIVE_QUESTIONNAIRE';

export const RESTORE_QUESTIONNAIRE = 'RESTORE_QUESTIONNAIRE';

export const COMPOUND_QUESTIONNAIRE = 'COMPOUND_QUESTIONNAIRE';

export const ADD_TEXT_OPTION = 'ADD_TEXT_OPTION';